import { get, writable } from 'svelte/store';
import type { GeoJSONStoreFeatures, GeoJSONStoreGeometries, TerraDraw } from 'terra-draw';

const snapshot = {
  ...writable<GeoJSONStoreFeatures<GeoJSONStoreGeometries>[]>([]),

  reset: () => snapshot.set([]),

  /**
   * Stores the current features from the draw instance
   * into the snapshot store.
   */
  collect(draw?: TerraDraw) {
    if (!draw) {
      return;
    }
    this.set(draw.getSnapshot());
  },

  /**
   * Replaces the current features in the draw instance with the
   * features stored in the snapshot.
   */
  restore(draw: TerraDraw) {
    draw.clear();

    // exlcude selection points and mid points that are generated by
    // terra draw for editing purposes
    const filteredFeatures = get(this).filter((f) => !f.properties.midPoint && !f.properties.selectionPoint);

    draw.addFeatures(filteredFeatures);
  },

  get featureCount(): number {
    return get(this).length;
  },

  get featureLayerIds(): string[] {
    const features = get(this);
    const layers = new Set<string>();

    for (const feature of features) {
      const parsedId = this._parseId(feature.id as string);
      if (parsedId) {
        layers.add(parsedId.layerId);
        continue;
      }
    }

    return Array.from(layers);
  },

  _parseId(id: string | number): { featureId: number; layerId: string } | null {
    function toNumberSafe(value: string | number): number | null {
      const num = Number(value);
      return Number.isNaN(num) ? null : num;
    }

    if (typeof id !== 'string') {
      return null;
    }

    const [featureIdString, ...rest] = id.split('.');
    const featureId = toNumberSafe(featureIdString);
    const layerId = rest.join('.');

    // require featureId to be an integer
    if (featureId === null || Number.isNaN(featureId) || !Number.isInteger(featureId)) {
      return null;
    }

    // require layerId to be non-empty
    if (layerId.length === 0) {
      return null;
    }

    return { featureId, layerId };
  },

  _lastMinId: 0,

  /**
   * Genrates a unique negative integer feature ID
   * (the server will transform these to positive integers
   * once the change is ready to be merged)
   */
  get nextTerraDrawFeatureId(): string {
    return `${this._lastMinId--}.terra-draw`;
  },
};

export { snapshot };
